version: "3.7"

services:
  mssql:
    build:
      context: ../.build/mssql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password@1233
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - cmsweb
    ports:
      - 1433:1433

networks:
  cmsweb: {}

volumes:
  sql_data:
